### ISSUE TITLE
Thanos Receivers with Kubecost 

### ISSUE THREAD

**Issue by heartTorres** [kubecost/docs#78] opened 2021-04-19 01:59 UTC
Hi,

We are using Thanos receivers in our cluster.
We have implemented Kubecost, in the documentation, it uses thanos side car in prometheus
but we are using Thanos Receivers to avoid tightly coupled with prometheus.

We'd like to configure the kubecost to use our thanos receivers but I couldn't find in the documentation.
Hope someone can help me.

**Comment by dwbrown2** [comment] 2021-04-19 03:02
Closing as a duplicate of https://github.com/kubecost/cost-analyzer-helm-chart/issues/856

**Closed by dwbrown2** 2021-04-19 03:02 UTC
